version: '3.8'

services:

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env
    environment:

      REDIS_URL: redis://redis:6379/0

    volumes:
      - .:/app


  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data


volumes:
  redis_data: