"""fixes

Revision ID: 27dabe7c6e5c
Revises: bc2ecb0d0866
Create Date: 2025-05-26 19:45:47.497310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27dabe7c6e5c'
down_revision: Union[str, None] = 'bc2ecb0d0866'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weather_codes', 'emoji',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.String(length=25),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weather_codes', 'emoji',
               existing_type=sa.String(length=25),
               type_=sa.VARCHAR(length=3),
               existing_nullable=False)
    # ### end Alembic commands ###
